# Generated by Django 3.1.5 on 2021-02-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_options', models.IntegerField(default=1)),
                ('amt_options', models.FloatField(default=200)),
                ('amt_shares', models.FloatField(default=200)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
